Repository security-vigilante/geekhub, pull requests merged in 2024-08, with the labels that each got.

#4 [Chore] 프로젝트 초기 세팅
  .commitlintrc.json
  .eslintignore
  .eslintrc.json
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/icons/.gitkeep
  public/images/.gitkeep
  src/apis/.gitkeep
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/app/login/.gitkeep
  src/app/my-library/.gitkeep
  src/app/vulnerability-db/.gitkeep
  src/components/.gitkeep
  src/hooks/.gitkeep
  src/libs/.gitkeep
  src/stores/.gitkeep
  src/stories/.gitkeep
  src/styles/globals.css
  src/types/.gitkeep
  src/utils/.gitkeep
  tailwind.config.ts
  tsconfig.json
Labels: ⚙ Setting

#13 [Hotfix] CI 설정 파일 업데이트
  .github/workflows/ ci.yml
Labels: 🐞 Fix

#15 [Hotfix] Node.js 버전 설정 관련 CI 설정 파일 업데이트
  .github/workflows/ ci.yml
Labels: 🐞 Fix

#17 [Hotfix] CI 파일명 수정
  .github/workflows/ci.yml
Labels: 🐞 Fix

#19 [Hotfix] CI 파일 test 스크립트 삭제
  .github/workflows/ci.yml
Labels: 🐞 Fix

#10 [Feat] Header,Footer,Pagination 컴포넌트 퍼블리싱
  .commitlintrc.json
  .eslintignore
  .eslintrc.json
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/icons/.gitkeep
  public/icons/footerBackground.svg
  public/icons/headerLogo.svg
  public/icons/paginationArrow.svg
  public/icons/spacSpaceLogo.svg
  public/images/.gitkeep
  src/apis/.gitkeep
  src/app/(home)/page.tsx
  src/app/(test)/min/[id]/page.tsx
  src/app/(test)/min/page.tsx
  src/app/layout.tsx
  src/app/login/.gitkeep
  src/app/my-library/.gitkeep
  src/app/vulnerability-db/.gitkeep
  src/components/.gitkeep
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Pagination/Pagination.tsx
  src/hooks/.gitkeep
  src/libs/.gitkeep
  src/stores/.gitkeep
  src/stories/.gitkeep
  src/styles/globals.css
  src/types/.gitkeep
  src/utils/.gitkeep
  tailwind.config.ts
  tsconfig.json
Labels: ✨ Component

#25 [Feat] chips 컴포넌트 퍼블리싱
  .github/workflows/chromatic.yml
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/icons/.gitkeep
  public/icons/caret.svg
  public/icons/document.svg
  public/icons/remove.svg
  public/index.ts
  src/app/(test)/ye/page.tsx
  src/components/.gitkeep
  src/components/Chips/AssistChip.tsx
  src/components/Chips/FilterChip.tsx
  src/components/Chips/InputChip.tsx
  src/components/Chips/SuggestionChip.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Pagination/Pagination.tsx
  src/stories/chips/AssistChip.stories.ts
  src/stories/chips/FilterChip.stories.ts
  src/stories/chips/InputChip.stories.ts
  src/stories/chips/SuggestionChip.stories.ts
  tailwind.config.ts
Labels: ✨ Component, ✅ Test, 🌏 Deploy

#22 [Feat] Button 컴포넌트 퍼블리싱
  src/app/(test)/sb/page.tsx
  src/components/Button/Button.tsx
  src/stories/button/Button.stories.ts
Labels: ✨ Component

#36 [Fix] Button 컴포넌트 크기 조정
  src/components/Button/Button.tsx
Labels: 🐞 Fix

#31 [Feat] Progress bar 컴포넌트 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/app/(test)/dh/page.tsx
  src/components/ProgressBar/ProgressBar.tsx
Labels: ✨ Component

#32 [Feat] Input 컴포넌트 퍼블리싱
  src/app/(test)/sb/page.tsx
  src/components/Input/Input.tsx
Labels: ✨ Component

#34 [Feat] Card 컴포넌트 퍼블리싱
  package.json
  pnpm-lock.yaml
  public/icons/bigPinIcon.svg
  public/icons/dbCardArrow.svg
  public/icons/detectFileCardButton.svg
  public/icons/externalLinkIcon.svg
  public/icons/pinIcon.svg
  public/icons/sharingIcon.svg
  public/images/DBCardDummyImg1.png
  public/images/DBCardDummyImg2.png
  public/images/DBCardDummyImg3.png
  public/index.ts
  src/app/(test)/min/[id]/page.tsx
  src/app/(test)/min/page.tsx
  src/app/(test)/ye/page.tsx
  src/components/Card/ArticleCard.tsx
  src/components/Card/ArticleSmallCard.tsx
  src/components/Card/DBCard.tsx
  src/components/Card/DetectFileCard.tsx
  src/components/Card/ScrapCard.tsx
  src/components/Chips/SuggestionChip.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Pagination/Pagination.tsx
  src/stories/chips/SuggestionChip.stories.ts
  tailwind.config.ts
Labels: ✨ Component, 🔨 Refactor

#37 [Feat] modal 컴포넌트
  pnpm-lock.yaml
  public/icons/bug.svg
  public/icons/headerLogo.svg
  public/index.ts
  src/app/(test)/ye/page.tsx
  src/app/layout.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Modals/ModalButton.tsx
  src/components/Modals/ModalRoot.tsx
  src/components/Modals/ModalText.tsx
  src/components/Modals/ModalTitle.tsx
  src/components/Modals/index.ts
  src/components/common/CheckedFileItem.tsx
  src/components/common/CheckedFileList.tsx
  src/components/common/Dimmed.tsx
  src/hooks/.gitkeep
  src/hooks/useModal.ts
  src/hooks/useOutsideClick.ts
  src/stories/.gitkeep
  src/stories/modals/Modal.stories.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Component

#48 [Chore] Vercel 배포
  .github/workflows/deploy.yml
  build.sh
Labels: 🌏 Deploy

#30 [Feat] InfoBox 컴포넌트 퍼블리싱
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/(home)/page.tsx
  src/app/(test)/jin/page.tsx
  src/app/(test)/min/[id]/page.tsx
  src/components/InfoBox/InfoBox.tsx
  tsconfig.json
Labels: ✨ Component

#29 [Feat] Floating 컴포넌트 퍼블리싱
  .env
  .eslintrc.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/icons/floatChat.svg
  public/icons/floatVector.svg
  public/index.ts
  src/app/(test)/jin/page.tsx
  src/app/(test)/ye/page.tsx
  src/components/Chips/SuggestionChip.tsx
  src/components/Floating/FloatingButton.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Pagination/Pagination.tsx
  src/stories/chips/SuggestionChip.stories.ts
Labels: ✨ Component
