Repository security-vigilante/geekhub, pull requests merged in 2024-09, with the labels that each got.

#56 [Hotfix] 환경변수 삭제
  .env
Labels: 🐞 Fix

#41 [Feat] list 컴포넌트 퍼블리싱
  public/icons/analyze.svg
  public/icons/doubleCheck.svg
  public/icons/emptyBookMark.svg
  public/icons/error.svg
  public/icons/folder.svg
  public/icons/fullBookMark.svg
  public/icons/listCheck.svg
  public/icons/listDocument.svg
  public/icons/listLibrary.svg
  public/icons/success.svg
  public/index.ts
  src/app/(test)/dh/page.tsx
  src/components/List/FileItem.tsx
  src/components/List/FolderItem.tsx
  src/components/List/ListHeader.tsx
  src/components/List/ScanStatus.tsx
  src/components/ProgressBar/ProgressBar.tsx
  src/types/.gitkeep
  src/types/list.d.ts
Labels: ✨ Component

#43 [Feat] 취약점 db 페이지 퍼블리싱
  .gitignore
  pnpm-lock.yaml
  public/icons/bannerCardArrow.svg
  public/icons/detectFileCardArrow.svg
  public/icons/detectFileCardBug.svg
  public/icons/detectFileCardButton.svg
  public/icons/detectFileCardStar.svg
  public/icons/searchIcon.svg
  public/images/BannerCardDummyImg1.png
  public/images/BannerCardDummyImg2.png
  public/images/BannerCardDummyImg3.png
  public/index.ts
  src/app/(test)/min/page.tsx
  src/app/agreements/page.tsx
  src/app/ppa/page.tsx
  src/app/vulnerability-db/.gitkeep
  src/app/vulnerability-db/[id]/page.tsx
  src/app/vulnerability-db/_components/ArticleCardList.tsx
  src/app/vulnerability-db/_components/ArticleDetail.tsx
  src/app/vulnerability-db/_components/BannerCardList.tsx
  src/app/vulnerability-db/_components/TopicList.tsx
  src/app/vulnerability-db/page.tsx
  src/components/Card/DBCard.tsx
  src/components/Card/DetectFileCard.tsx
  src/components/Card/ScrapCard.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Input/VulDbSearchInput.tsx
  src/components/LibraryCard/DetectFileCard.tsx
  src/components/LibraryCard/ScrapCard.tsx
  src/components/VulDbCard/ArticleCard.tsx
  src/components/VulDbCard/ArticleSmallCard.tsx
  src/components/VulDbCard/BannerCard.tsx
  src/types/articleCard.d.ts
Labels: 📖 Page, 🎨 Style

#51 [Feat] My 저장소 전반부 페이지 퍼블리싱
  public/icons/caretLeft.svg
  public/icons/caretRight.svg
  public/icons/clockCounterClockwise.svg
  public/icons/folderSimpleStar.svg
  public/icons/signOut.svg
  public/images/.gitkeep
  public/images/AvatarDummyImg.png
  public/images/headerBackground.svg
  public/index.ts
  src/app/me/_components/ContactForm.tsx
  src/app/me/_components/ContactInfo.tsx
  src/app/me/_components/ContactSection.tsx
  src/app/me/_components/MePageLinks.tsx
  src/app/me/_components/MePageTitle.tsx
  src/app/me/_components/ScrapList.tsx
  src/app/me/_components/UserInfo.tsx
  src/app/me/_components/UserSetting.tsx
  src/app/me/contact/page.tsx
  src/app/me/page.tsx
  src/app/me/scraps/page.tsx
  src/app/me/setting/page.tsx
  src/app/my-library/.gitkeep
  src/app/repos/_components/ReposPageHeader.tsx
  src/app/repos/_components/RepositoryActions.tsx
  src/app/repos/_components/RepositoryList.tsx
  src/app/repos/_components/UserCard.tsx
  src/app/repos/page.tsx
  src/components/Button/Button.tsx
  src/components/Input/Input.tsx
  src/components/LibraryCard/DetectFileCard.tsx
  src/components/LibraryCard/ScrapCard.tsx
  src/types/detectedFileCard.d.ts
  src/types/scrapCard.d.ts
Labels: 📖 Page, 🎨 Style

#58 [Feat] 챗봇 컴포넌트
  .gitignore
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/icons/bug.svg
  public/icons/chat.svg
  public/icons/send.svg
  public/index.ts
  src/apis/.gitkeep
  src/apis/llama.ts
  src/app/(test)/ye/page.tsx
  src/app/api/generateMessage/route.ts
  src/components/Chatbot/Chatbot.tsx
  tailwind.config.ts
Labels: ✨ Component, 📬 API

#61 [Feat] 취약점 검색 페이지 및 chip 컴포넌트 수정
  package.json
  pnpm-lock.yaml
  src/app/api/search/route.ts
  src/app/api/topics/route.ts
  src/app/vulnerability-db/_components/TopicList.tsx
  src/app/vulnerability-db/page.tsx
  src/components/Chatbot/Chatbot.tsx
  src/components/Chips/FilterChip.tsx
  src/components/Input/VulDbSearchInput.tsx
  src/components/common/Loading/LogoLoading.tsx
  tailwind.config.ts
Labels: ✨ Component, 📬 API

#71 [Feat] 폰트 및 헤더 수정, 로그아웃 구현
  public/PretendardVariableSubset.woff2
  src/app/_components/Introduction.tsx
  src/app/layout.tsx
  src/components/Header/Header.tsx
  src/components/SpinningBox.tsx
  tailwind.config.ts
Labels: 🎨 Style, 🔨 Refactor

#73 [Feat] 북마크기능,페이지, 애니메이션수정, 모달수정
  package.json
  pnpm-lock.yaml
  public/icons/bigPinIcon.svg
  public/icons/externalLinkIcon.svg
  public/icons/fillPin.svg
  public/icons/kakao.svg
  public/icons/link.svg
  public/icons/outlinePin.svg
  public/icons/pinIcon.svg
  public/icons/sharing.svg
  public/icons/sharingIcon.svg
  public/index.ts
  src/app/_components/AOSwrapper.tsx
  src/app/_components/Carousel.tsx
  src/app/_components/Hero.tsx
  src/app/_components/Introduction.tsx
  src/app/_components/Overview.tsx
  src/app/api/scrap/route.ts
  src/app/api/vulDb/[id]/route.ts
  src/app/api/vulDb/route.ts
  src/app/api/vulDb/updateCrawling/route.ts
  src/app/layout.tsx
  src/app/me/_components/ContactInfo.tsx
  src/app/me/scraps/page.tsx
  src/app/repos/_components/RepositoryList.tsx
  src/app/vulnerability-db/[id]/page.tsx
  src/app/vulnerability-db/_components/ArticleCardList.tsx
  src/app/vulnerability-db/_components/ArticleDetail.tsx
  src/app/vulnerability-db/_components/ScrapButton.tsx
  src/app/vulnerability-db/_components/ShareButton.tsx
  src/app/vulnerability-db/page.tsx
  src/components/Chatbot/Chatbot.tsx
  src/components/Header/Header.tsx
  src/components/LibraryCard/ScrapCard.tsx
  src/components/Modals/ModalRoot.tsx
  src/components/VulDbCard/ArticleCard.tsx
  src/components/VulDbCard/ArticleSmallCard.tsx
  src/hooks/useKakaoShare.ts
  src/libs/.gitkeep
  src/types/aos.d.ts
  src/types/articleCard.d.ts
  src/types/crawlingData.d.ts
  src/types/kakao.d.ts
  tailwind.config.ts
Labels: ✨ Component, 📖 Page, 🐞 Fix, 📬 API

#76 [Feat ]레포지토리 검사 페이지 기능 고도화
  package.json
  pnpm-lock.yaml
  public/icons/listCheck.svg
  src/apis/repos/repository.ts
  src/app/api/getCodeScanResult/route.ts
  src/app/api/getFileStatus/route.ts
  src/app/repos/[userName]/[repoName]/_components/MultipleSelectModal.tsx
  src/app/repos/[userName]/[repoName]/_components/RepoSide.tsx
  src/app/repos/[userName]/[repoName]/_components/ScanFormat.tsx
  src/app/repos/[userName]/[repoName]/_components/Title.tsx
  src/app/repos/[userName]/[repoName]/layout.tsx
  src/app/repos/[userName]/[repoName]/repo_inspection/_components/resultFormat.tsx
  src/components/InfoBox/InfoBox.tsx
  src/components/List/Checkbox.tsx
  src/components/List/FileItem.tsx
  src/components/List/FolderItem.tsx
  src/components/List/ListHeader.tsx
  src/stores/useRepoDetailStore.ts
  src/types/codeScan.d.ts
Labels: ✨ Component, 🔨 Refactor, 🐞 Fix, 📬 API

#80 Fix: BannerList 애니매이션 수정
  src/components/VulDbCard/BannerCard.tsx
Labels: 🐞 Fix

#78 [Refactor] 오류 수정 및 개선
  public/icons/githubCat.svg
  public/index.ts
  src/app/_components/Overview.tsx
  src/app/layout.tsx
  src/app/login/_component/Login.tsx
  src/app/me/_components/ContactForm.tsx
  src/app/me/_components/ContactInfo.tsx
  src/app/me/_components/UserInfo.tsx
  src/app/repos/[userName]/[repoName]/_components/RepoSide.tsx
  src/app/repos/[userName]/[repoName]/_components/ScanFormat.tsx
  src/app/repos/_components/LogoutModal.tsx
  src/app/repos/_components/RepositoryActions.tsx
  src/app/repos/_components/UserCard.tsx
  src/app/vulnerability-db/_components/ArticleDetail.tsx
  src/app/vulnerability-db/_components/TopicList.tsx
  src/components/Button/Button.tsx
  src/components/Chips/AssistChip.tsx
  src/components/Chips/FilterChip.tsx
  src/components/Chips/InputChip.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Input/Input.tsx
  src/components/LibraryCard/ScrapCard.tsx
  src/components/Modals/ModalButton.tsx
  src/components/Switch/Switch.tsx
  src/components/VulDbCard/ArticleCard.tsx
  src/components/VulDbCard/ArticleSmallCard.tsx
  src/firebase/firebaseRepository.ts
  src/hooks/useLogout.ts
  tailwind.config.ts
Labels: 🎨 Style, 🔨 Refactor, 🐞 Fix

#83 [Refactor] 오류 해결 및 성능 개선
  src/app/api/vulDb/[id]/route.ts
  src/app/repos/[userName]/[repoName]/_components/RepoSide.tsx
  src/app/repos/[userName]/[repoName]/_components/ScanFormat.tsx
  src/app/repos/[userName]/[repoName]/repo_inspection/_components/resultFormat.tsx
  src/components/Alert/Alert.tsx
  src/components/List/FileItem.tsx
Labels: ✨ Component, 🔨 Refactor, 🐞 Fix

#85 [Refactor] 오류 해결 성능 개선
  next.config.mjs
  src/app/api/repositories/status/route.ts
  src/app/repos/_components/RepositoryList.tsx
  src/components/LibraryCard/DetectFileCard.tsx
  src/components/Pagination/Pagination.tsx
  src/firebase/firebaseRepository.ts
  src/utils/getSortParameters.ts
Labels: 🔨 Refactor, 🐞 Fix
